data &zbior._score;
    set &zbior;

SCORECARD_POINTS = 0;

/* ===================== ACT_AGE ===================== */
select;
    when ( ACT_AGE > 80 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 70);
        PSC_ACT_AGE = 70;
    end;
    when ( 61 < ACT_AGE <= 62 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 46);
        PSC_ACT_AGE = 46;
    end;
    when ( 68 < ACT_AGE <= 80 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 44);
        PSC_ACT_AGE = 44;
    end;
    when ( not missing(ACT_AGE) and ACT_AGE <= 50 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 33);
        PSC_ACT_AGE = 33;
    end;
    when ( 62 < ACT_AGE <= 68 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 34);
        PSC_ACT_AGE = 34;
    end;
    when ( 50 < ACT_AGE <= 61 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 24);
        PSC_ACT_AGE = 24;
    end;
    otherwise do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 24);
        PSC_ACT_AGE = 24;
    end;
end;

/* ===================== ACT_CALL_CC ===================== */
select;
    when ( not missing(ACT_CALL_CC) and ACT_CALL_CC <= 1.1900674433 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 64);
        PSC_ACT_CALL_CC = 64;
    end;
    when ( 1.1900674433 < ACT_CALL_CC <= 1.4502074689 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 51);
        PSC_ACT_CALL_CC = 51;
    end;
    when ( 1.4502074689 < ACT_CALL_CC <= 1.5775700935 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 43);
        PSC_ACT_CALL_CC = 43;
    end;
    when ( ACT_CALL_CC > 2.0091145833 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 34);
        PSC_ACT_CALL_CC = 34;
    end;
    when ( 1.5775700935 < ACT_CALL_CC <= 2.0091145833 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 24);
        PSC_ACT_CALL_CC = 24;
    end;
    otherwise do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 24);
        PSC_ACT_CALL_CC = 24;
    end;
end;

/* ===================== ACT_CCSS_DUEUTL ===================== */
select;
    when ( missing(ACT_CCSS_DUEUTL) ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 57);
        PSC_ACT_CCSS_DUEUTL = 57;
    end;
    when ( ACT_CCSS_DUEUTL <= 0.0208333333 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 54);
        PSC_ACT_CCSS_DUEUTL = 54;
    end;
    when ( 0.0208333333 < ACT_CCSS_DUEUTL <= 0.025 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 41);
        PSC_ACT_CCSS_DUEUTL = 41;
    end;
    when ( 0.025 < ACT_CCSS_DUEUTL <= 0.0416666667 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 33);
        PSC_ACT_CCSS_DUEUTL = 33;
    end;
    when ( ACT_CCSS_DUEUTL > 0.21875 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 29);
        PSC_ACT_CCSS_DUEUTL = 29;
    end;
    when ( 0.0416666667 < ACT_CCSS_DUEUTL <= 0.21875 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 24);
        PSC_ACT_CCSS_DUEUTL = 24;
    end;
    otherwise do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 24);
        PSC_ACT_CCSS_DUEUTL = 24;
    end;
end;

/* ===================== ACT_CCSS_MIN_LNINST ===================== */
select;
    when ( missing(ACT_CCSS_MIN_LNINST) ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 47);
        PSC_ACT_CCSS_MIN_LNINST = 47;
    end;
    when ( 0 < ACT_CCSS_MIN_LNINST <= 1 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 40);
        PSC_ACT_CCSS_MIN_LNINST = 40;
    end;
    when ( ACT_CCSS_MIN_LNINST > 11 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 32);
        PSC_ACT_CCSS_MIN_LNINST = 32;
    end;
    when ( not missing(ACT_CCSS_MIN_LNINST) and ACT_CCSS_MIN_LNINST <= 0 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 31);
        PSC_ACT_CCSS_MIN_LNINST = 31;
    end;
    when ( 7 < ACT_CCSS_MIN_LNINST <= 11 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 26);
        PSC_ACT_CCSS_MIN_LNINST = 26;
    end;
    when ( 1 < ACT_CCSS_MIN_LNINST <= 7 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 24);
        PSC_ACT_CCSS_MIN_LNINST = 24;
    end;
    otherwise do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 24);
        PSC_ACT_CCSS_MIN_LNINST = 24;
    end;
end;

/* ===================== ACT_CCSS_N_STATC ===================== */
select;
    when ( ACT_CCSS_N_STATC > 21 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 82);
        PSC_ACT_CCSS_N_STATC = 82;
    end;
    when ( missing(ACT_CCSS_N_STATC) ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 53);
        PSC_ACT_CCSS_N_STATC = 53;
    end;
    when ( 10 < ACT_CCSS_N_STATC <= 21 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 51);
        PSC_ACT_CCSS_N_STATC = 51;
    end;
    when ( 4 < ACT_CCSS_N_STATC <= 10 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 34);
        PSC_ACT_CCSS_N_STATC = 34;
    end;
    when ( not missing(ACT_CCSS_N_STATC) and ACT_CCSS_N_STATC <= 0 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 32);
        PSC_ACT_CCSS_N_STATC = 32;
    end;
    when ( 0 < ACT_CCSS_N_STATC <= 4 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 24);
        PSC_ACT_CCSS_N_STATC = 24;
    end;
    otherwise do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 24);
        PSC_ACT_CCSS_N_STATC = 24;
    end;
end;

/* ===================== AGS3_MEAN_CMAXA_DUE ===================== */
select;
    when ( AGS3_MEAN_CMAXA_DUE <= 0.3333333333 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 73);
        PSC_AGS3_MEAN_CMAXA_DUE = 73;
    end;
    when ( 0.3333333333 < AGS3_MEAN_CMAXA_DUE <= 0.6666666667 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 62);
        PSC_AGS3_MEAN_CMAXA_DUE = 62;
    end;
    when ( 0.6666666667 < AGS3_MEAN_CMAXA_DUE <= 1.3333333333 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 47);
        PSC_AGS3_MEAN_CMAXA_DUE = 47;
    end;
    when ( AGS3_MEAN_CMAXA_DUE > 1.3333333333 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 24);
        PSC_AGS3_MEAN_CMAXA_DUE = 24;
    end;
    otherwise do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 24);
        PSC_AGS3_MEAN_CMAXA_DUE = 24;
    end;
end;

/* ===================== APP_NUMBER_OF_CHILDREN ===================== */
select;
    when ( APP_NUMBER_OF_CHILDREN > 1 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 57);
        PSC_APP_NUMBER_OF_CHILDREN = 57;
    end;
    when ( 0 < APP_NUMBER_OF_CHILDREN <= 1 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 33);
        PSC_APP_NUMBER_OF_CHILDREN = 33;
    end;
    when ( not missing(APP_NUMBER_OF_CHILDREN) and APP_NUMBER_OF_CHILDREN <= 0 ) do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 24);
        PSC_APP_NUMBER_OF_CHILDREN = 24;
    end;
    otherwise do;
        SCORECARD_POINTS = sum(SCORECARD_POINTS, 24);
        PSC_APP_NUMBER_OF_CHILDREN = 24;
    end;
end;

run;
/* proc npar1way data=data_sc.abt_app_score edf; */
/*     class default12; */
/*     var SCORECARD_POINTS; */
/* run; */
